### ISSUE TITLE
Failure of Travis on Windows due to Unix style paths

### ISSUE THREAD

**Issue by HeroicKatora** [image-rs/image-png#125]
The current builds fails on Travis due to an issue with the png testsuite?? For some reason, some file is not checked [resulting in](https://travis-ci.org/image-rs/image-png/jobs/526332943)

> `thread 'render_images' panicked at 'reference for "\"tests\\\\pngsuite\\\\s35n3p04.png\"" is missing', src\libcore\option.rs:1038:5`

Interestingly the file is not consistent and nightly fails [with another image instead](https://travis-ci.org/image-rs/image-png/jobs/526332944):

> `thread 'render_images' panicked at 'reference for "\"tests\\\\pngsuite\\\\basi6a08.png\"" is missing', src\libcore\option.rs:1036:5`

I'm confused. Is the directory checkout incomplete or is this an issue with the `glob` library or with the manner we iterate the images?

**Comment by pix64** [comment]
The order has to do with the hashmap implementation differences.

**Comment by pix64** [comment]
Somehow the path being inserted into ref_results has backslashes converted to to slashes.

This is the string which gets inserted into ref_results: "\"tests/pngsuite/basi3p04.png\""
This is the string which is expected to be in ref_results: "\"tests\\\\pngsuite\\\\basi3p04.png\""

**Comment by HeroicKatora** [comment]
Oh, so the order (and thus the first we panic on) is just different because of non-deterministic hashing operation? That makes sense, actually.

**Comment by martinlindhe** [comment]
It's reproducible on my windows box, so I'm having a look at this atm
