### ISSUE TITLE
Remove duplicated crc32 algorithm

### ISSUE THREAD

**Issue by martinlindhe** [image-rs/image-png#127]
There's a crc32 implementation in src/crc.rs

A duplicate also lives in tests/check_testimages.rs

This issue is for reusing the code from src/crc.rs and deleting the duplicated code in tests/check_testimages.rs

**Comment by martinlindhe** [comment]
As mentioned in #128, another option could be to instead depend on a external crate for crc32. Any opinions?

**Comment by HeroicKatora** [comment]
I'd only depend on an external crate if it doesn't have dependencies. The `crc` crate seems a bit to immature for me, has too wide of a scope and for some reason generates its tables a build time?

Another criterion could be performance. `crc32fast` offers –according to its own benchmark–six times the throughput at 1499 MB/s and up to 7314 MB/s on `sse` platforms. That could be worth a great deal of tradeoff, for example in additional dependencies and would lower our maintenance burder.

**Comment by martinlindhe** [comment]
I'll make a PR using crc32fast and we can take it from there

**Comment by martinlindhe** [comment]
I have a crc32fast branch working, but it currently depends on https://github.com/srijs/rust-crc32fast/pull/8 in order to work.

I'm awaiting follow up on that PR before I can go ahead and open a PR for this.
Meanwhile my branch lives in https://github.com/martinlindhe/image-png/tree/crc32fast

**Comment by HeroicKatora** [comment]
I think `State` implements `Clone`, so `self.current_chunk.0.finalize()` should work as well.

**Comment by martinlindhe** [comment]
Thanks, I'll have a look at that

**Comment by martinlindhe** [comment]
> 
> 
> I think `State` implements `Clone`, 

It does not. I added Clone to State & U32Value but same issue.

> so `self.current_chunk.0.finalize()` could work as well.

This is what the code's already doing and is the issue resolved by https://github.com/srijs/rust-crc32fast/pull/8

**Comment by HeroicKatora** [comment]
Oops, that should have been `self.current_chunk.0.clone().finalize()`. Corrected it above. But rust-crc32fast does implement it for [State](https://github.com/srijs/rust-crc32fast/blob/master/src/baseline.rs#L3). I'm a bit confused, why is that not accessible?

**Comment by martinlindhe** [comment]
Just me being confused too :-) I was looking at this State: https://github.com/image-rs/image-png/blob/master/src/decoder/stream.rs#L29

**Comment by martinlindhe** [comment]
> Oops, that should have been `self.current_chunk.0.clone().finalize()`. Corrected it above. 

Yep, this works! Rebasing etc
