### ISSUE TITLE
"Currently pngcheck is the most usable part" in README

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image-png#145]
The README currently reads:

> PNG decoder/encoder in pure Rust. Currently pngcheck is the most usable part. Build with cargo build --release --example pngcheck.

This undersells the crate a bit :stuck_out_tongue_closed_eyes: 

It currently supports encoding and decoding PNG in a variety of bit depths. Including streaming encoding and decoding. Plus decoding APNG? It would be nice to document all of that.

**Comment by HeroicKatora** [comment]
Fixed in #155 , forgot to close this though. It's still very brief but that does not seem like a bad thing.
