### ISSUE TITLE
Writer should provide into_inner function

### ISSUE THREAD

**Issue by wwylele** [image-rs/image-png#160]
Sorry if I am in the wrong direction with my problem. I want to encode a PNG in-memory instead of to a file, so here is what I tried:
```rust
let cursor = std::io::Cursor::new(Vec::new());
let encoder = png::Encoder::new(cursor, ...,...); // the cursor is consumed here
encoder.set...;
let writer = encoder.write_header().unwrap();
writer.write_image_data(...).unwrap();
// how do I get back the buffer?
let cursor = writer.into_inner(); // ???
let result = cursor.into_inner();
```
There isn't a `into_inner` function I expected to let me get back the cursor object, and I can't find other way to get the result data.

**Comment by HeroicKatora** [comment]
An implementation of `Write` is also provided for `&mut Cursor`, so you could utilize that as an alternative/workaround. Agreed however, that `into_inner` would be the cleaner way to express ownership of the writer and avoid lifetime bounds when storing it somewhere. In the meantime:

```rust
let mut cursor = std::io::Cursor::new(Vec::new());
let encoder = png::Encoder::new(&mut cursor, ...,...);
encoder.set...;
let writer = encoder.write_header().unwrap();
writer.write_image_data(...).unwrap();
let result = cursor.into_inner();
```
