### ISSUE TITLE
Unsupported Transformations should panic (or become supported)

### ISSUE THREAD

**Issue by SolraBizna** [image-rs/image-png#172]
`Transformations` provides a wide set of transformations, analogous to the ones in `libpng`. However, nearly all of them are unimplemented. If you try to use the unimplemented transformations, currently they are silently ignored. It seems to me that unsupported transformations should panic, rather than producing unexpected results. If someone writes code today using (for instance) `Transformations::SWAP_ALPHA` and expects to get alpha-first data as a result, they're in for an unhappy surprise. Or, worse, if someone writes that code and unknowingly assumes that the alpha-last data they're getting is what they're always going to get... and then some day `SWAP_ALPHA` gets implemented...

**Comment by fintelia** [comment]
With the nit that it is generally better to return errors rather than panic on invalid input, I agree with this suggestion
