### ISSUE TITLE
Panic during save_with_format when width == 0

### ISSUE THREAD

**Issue by filcuc** [image-rs/image-png#179]
To reproduce:
1) load an image with size 1x150
```
let reader = BufReader::new(file);
let image = image::load(reader, image_format).map_err(|_| "Failed to load file".to_owned())?;
let w = image.width();  // 1
let h = image.height(); // 150
```
2) create thumbnail with size 128x128.
```
let thumbnail = Some(image.thumbnail(128, 128));
let w = thumbnail.width();   // 0
let h = thumbnail.height();  // 128
```
3) Save image
```
thumbnail.save_with_format(
   "/path/to/somwhere,
   image::ImageFormat::PNG,
)
```
4) Panic

**Comment by HeroicKatora** [comment]
Thanks for the report. I was able to distill the reproduction:

```
image::RgbImage::new(0, 0).save_with_format("/tmp/foo.png", image::ImageFormat::PNG);
```

<details>
<summary>A relevant portion from the stacktrace (also with version numbers):</summary>
<pre>
  16: png::encoder::Writer<W>::write_image_data
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/png-0.15.2/src/encoder.rs:154
  17: image::png::PNGEncoder<W>::encode
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.22.3/./src/png.rs:160
  18: image::io::free_functions::save_buffer_with_format_impl
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.22.3/./src/io/free_functions.rs:198
  19: image::dynimage::save_buffer_with_format
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.22.3/./src/dynimage.rs:794
  20: image::buffer::ImageBuffer<P,Container>::save_with_format
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.22.3/./src/buffer.rs:786
</pre>
</details>

**Comment by filcuc** [comment]
Related to this is that i've obtained the image with width = 0 during thumb creation. I think that maybe resize should take in account this corner case a put a `max(computed_width, 1)`

**Comment by HeroicKatora** [comment]
This is offtopic but documented accordingly:

> The image's aspect ratio is preserved.

You can always workaround by using your own size calculation and `thumbnail_exact` instead. If you want to propose changing the calculated sizes then you should create an issue in `image`.

**Comment by kaj** [comment]
The preservation of aspect ratio is always an approximation anyway, so I don't think that is a problem.  As @fintelia noted in #180, a zero-width image can not be encoded as a valid png anyway.

So while panics should be avoided, saving a zero-width (or zero-height) image as png should return some kind of error.  And a thumbnail should probably always be at least one pixel in each dimension.
