### ISSUE TITLE
Make Writer::stream_writer(_) take ownership of the underlying Writer or provide a Writer.into_strea_writer()

### ISSUE THREAD

**Issue by hank-der-hafenarbeiter** [image-rs/image-png#189]
Hey everyone,

I'm currently trying to use StreamWriter and Actix's SyncArbiter to calculate some pretty big images. The problem I run into is that StreamWriter borrows the underlying writer making it hard to use across threads. This would be a lot easier if I could get a StreamWriter that owns the underlying Writer.

**Comment by HeroicKatora** [comment]
Tagging this as `hard` as it potentially requires revising the data model if we want to avoid a breaking release. Since most of the internals are private we might be able to cheat our way and enable an owned writer that itself with the lifetime parameter `'static`.

**Comment by HeroicKatora** [comment]
As a general concept, we could take inspiration from `Cow::Owned`. Since it owns the object, the lifetime parameter can be chosen arbitrarily as it is only used in the borrowed state. We could introduce a similar enum internally, only requiring some matching on use which should be negligible overhead compared to the IO.

**Comment by hank-der-hafenarbeiter** [comment]
Going a route similar to the standard library might be a good idea: Vec::iter() borrows the vector Vec::into_iter() owns the vector. So there would - from my perspective - be no need to change any of the existing code. Add a 'into_stream_writer()' method to Writer and create a OwnedStreamWriter. I don't know how much work this would be, but it seems to avoid some of your concerns.
