### ISSUE TITLE
Support for encoding with adaptive filtering

### ISSUE THREAD

**Issue by okaneco** [image-rs/image-png#208]
This can considerably reduce the size of some images, but takes longer to execute.

The 4th paragraph of this section in the PNG standard recommends adaptive filtering for best compression.
https://www.w3.org/TR/PNG/#12Filter-selection

This paragraph better describes the method for adaptive filtering.
http://www.libpng.org/pub/png/book/chapter09.html#INDEX-688
> For grayscale and truecolor images of 8 or more bits per sample, with or without alpha channels, dynamic filtering is almost always beneficial. The approach that has by now become standard is known as the minimum sum of absolute differences heuristic and was first proposed by Lee Daniel Crocker in February 1995. In this approach, the filtered bytes are treated as signed values--that is, any value over 127 is treated as negative; 128 becomes -128 and 255 becomes -1. The absolute value of each is then summed, and the filter type that produces the smallest sum is chosen. This approach effectively gives preference to sequences that are close to zero and therefore is biased against filter type None.

**Comment by Shnatsel** [comment]
It's worth noting that https://github.com/brion/mtpng seems to already support this

**Comment by okaneco** [comment]
I've implemented adaptive filtering but it needs some design work. I can submit a PR for review if you think it's in the right direction.  
Here's the branch: https://github.com/okaneco/image-png/commit/0104fd716f3ac6e558f68c7187b8cbd532efd6d9

#### `FilterType` enum

I've added Adaptive to the enum with a value of 5. An issue I see is that Adaptive is not a valid decoding filter type. As an encoding filter, it delegates to the first five algorithms: NoFilter, Sub, Up, Avg, and Paeth and is used in `filter(...)`.

#### `unfilter(...)` in `filter.rs`

Return an Error on matching with Adaptive. Should filters be non-exhaustive? I'm not aware of heuristics that perform better than these 5+1 algorithms, and it doesn't make sense to match on Adaptive in decoding. Having an EncodingFilterType and DecodingFilterType seems redundant.

#### `filter(...)` in `filter.rs`

current signature
```rust
pub(crate) fn filter(method: FilterType, bpp: BytesPerPixel, previous: &[u8], current: &mut [u8]) 
```
modified signature
```rust
pub(crate) fn filter(method: FilterType, bpp: BytesPerPixel, previous: &[u8], current: &mut [u8]) -> u8
```

I've changed the function signature so it returns a u8 to signal the filter type. I wasn't sure of the best way to communicate this back to the writers that call `filter` so that they can write the filter byte to the scanline. This could also return a FilterType and cast to u8 at the caller sites.

I've moved the row operations for each filter into their own functions to avoid code duplication in the Adaptive match arm.

#### Tests/Benchmarks

I'm unsure of a test design or validation for the results.

I've compared all the filters for size and it seems to work (this is how I discovered #263) as expected. It's not the smallest file size for every image but it's consistently towards the better performing filters or even with Paeth. I've only tested with default compression level and Best level, the advantages of Adaptive diminish with the higher compression levels. It matches my past experience with using imagemagick's `-quality` for pngs where `-quality 95` should be roughly equivalent to Best compression and Adaptive filtering.

**Comment by fintelia** [comment]
Another option would be to pass around an `Option<FilterType>` and have the None value mean adaptive. I'd also favor using our FilterType enum rather than a raw u8 where possible.
