### ISSUE TITLE
Format Error Decoding APNG

### ISSUE THREAD

**Issue by sethierophant** [image-rs/image-png#209]
The image in question (NSFW): http://0x0.st/ipcn.png

Reposting from https://hierophant.club/q/19#124:

> The image in question had these chunks:
>
>     0 0x00000008      13 b'IHDR' 0xAD8152DD
>     1 0x00000021       6 b'bKGD' 0xF943BB7F
>     2 0x00000033       8 b'acTL' 0xB42DE9A0
>     3 0x00000047    8192 b'IDAT' 0xCA032E99
>     4 0x00002053    8192 b'IDAT' 0x8A463FCA
>     5 0x0000405F    8192 b'IDAT' 0xB2F86ABA
>     6 0x0000606B     132 b'IDAT' 0x868F6C4D
>     7 0x000060FB      26 b'fcTL' 0xBB744D2E
>     8 0x00006121 3224104 b'fdAT' 0x64BB731A
>     9 0x00319355       0 b'IEND' 0xAE426082
> Sequence number 0 is in the fcTL at 0x000060FB+8. Sequence number 1 is in the fdAT at 0x00006121+8. These are all the sequence numbers. The error contains #1811166872 which is 0x6bf43698. Those bytes only appear in the image at 0xe129. The offset from sequence number 1 is 0x8000=2^15. So image:: 116 took the fdAT length of 3224104, clamped it to 2^15(-12) and looked for the next non-existent sequence number there, even though there is no new chunk there at all. This clamping cannot be accidental and should be easy to spot.

And from https://hierophant.club/q/19#129:

> Here's what happens. In an APNG the fcTL and fdAT chunks have a sequence number in their first four payload bytes. One sequence number per chunk. By contrast, the code reads a sequence number at the start of every fdAT PartialChunk, not just the first one. This is insane because from the second one we're inside the deflate stream. The progression of states through goto! is PartialChunk → DecodeData → ReadChunk → PartialChunk. The solution is to differentiate between the first PartialChunk and subsequent ones, such as by introducing a flag that tells a PartialChunk whether it is the first one, and only read one sequence number per fdAT. The IDAT branch has the same issue but there it is harmless because all it does is set have_idat, which is idempotent.

Thanks!

**Comment by HeroicKatora** [comment]
The debugging already helps a lot with an issue of APNG decoding. This might be actually related to another issue we were having :+1:

**Comment by HeroicKatora** [comment]
Can you check if this is fixed by #210 ? This should also add/fix some more about apng frames, not only when the initial IDAT is used as a as a thumbnail. This means the caller needs to take care of assembling, overlaying, and disposing frames in the animation but the pixels and the frame meta data should be returned correctly.

**Comment by sethierophant** [comment]
Yep, that fixes the issue. Thanks for the quick response.

**Comment by HeroicKatora** [comment]
Is the newest release (`0.16.4`) enough, it likely is for fixing the thumbnail, or do you specifically rely on the follow-ups in the outstanding PR?

**Comment by sethierophant** [comment]
Yeah, I tested 0.16.4 and can confirm that it fixes the problem.
