### ISSUE TITLE
Request: transform to add an alpha channel.

### ISSUE THREAD

**Issue by Lokathor** [image-rs/image-png#239]
I'd like a transform that adds an alpha channel in the output, if the image doesn't have one.

Essentially I want to have it be able to make the output always be RGBA8, regardless of whatever the file happens to have. Currently you can turn u16 to u8, expand sub-8-bit samples to full bytes, and expand paletted images, but there seems to be no option to force in an alpha channel.

**Comment by simonbuchan** [comment]
This would be incredibly convenient for loading textures, since graphics hardware doesn't like 3-byte pixels. Expanding large images efficiently can be tricky.

**Comment by Shnatsel** [comment]
`tiny-skia` (port of a subset of Skia to Rust) also needs this: https://github.com/RazrFalcon/tiny-skia/blob/master/benches/README.md#png
