### ISSUE TITLE
Gamma encoding/decoding

### ISSUE THREAD

**Issue by ivovanderlans** [image-rs/image-png#243]
I'd like to add gamma encoding/decoding which I need for my project. It's just about reading and writing the gAMA chunk, so no transformations are involved (which seems a responsibility for the crate user). I have already created a local branch off the master branch, have run the tests (passing), verified the decoded values against the png test-suite, but have no permission to publish the branch, nor create a pull-request.

**Comment by HeroicKatora** [comment]
> nor create a pull-request.

Pull requests should be open for everyone. The way Github work you'll need to open them from your own fork of the repository :)

**Comment by ivovanderlans** [comment]
Ah, this is going to take a few days (this would be my first contribution to github-like systems)

**Comment by de-vri-es** [comment]
I believe your PR (#244) was merged, so this issue can be closed :tada:. Thank your for implementing it :D
