### ISSUE TITLE
Forbid unsafe code

### ISSUE THREAD

**Issue by ralpha** [image-rs/image-png#246]
`png` does not seem to use unsafe code, which is very good :)
And is great for an image library!

To prevent this from ever happening, add following line to the top:
```rust
#![forbid(unsafe_code)]
```
of https://github.com/image-rs/image-png/blob/master/src/lib.rs
Other workspace like https://github.com/image-rs/image-png/blob/master/png-afl/src/main.rs could also use this if you want to (and if possible).

This will make the package green in
https://github.com/anderejd/cargo-geiger

**Comment by fintelia** [comment]
I'm in favor of this. Want to create a pull request?

**Comment by ralpha** [comment]
Okay, I'll create a pull request.
