### ISSUE TITLE
Transformations::STRIP_ALPHA not appearing to work

### ISSUE THREAD

**Issue by LeonineKing1199** [image-rs/image-png#252]
Given the following code using the latest version of the lib and a humble RBGA PNG file:
```rust
let mut decoder = png::Decoder::new(reader);
decoder
    .set_transformations(::png::Transformations::STRIP_ALPHA);

let (info, mut png_reader) = decoder.read_info()?;

let ::png::OutputInfo { height, width, .. } = info;

let mut buf = vec![0u8; height as usize * width as usize * 3];
png_reader.next_frame(&mut buf)?;
```
This code will return an `Err` type at: `png_reader.next_frame(&mut buf)?;` with the complain that the input buffer isn't sufficiently large.

If I manually update the `3` to a `4` then it works which means that the alpha channel isn't being stripped during the decoding process.

More condensed, this fails:
```rust
let mut decoder = ::png::Decoder::new(reader);
decoder.set_transformations(::png::Transformations::STRIP_ALPHA);

let (info, mut png_reader) = decoder.read_info()?;

assert_eq!(
    png_reader.output_color_type(),
    (::png::ColorType::RGB, ::png::BitDepth::Eight)
);
```
with:
```
thread 'cvr_png_swap_channels' panicked at 'assertion failed: `(left == right)`
  left: `(RGBA, Eight)`,
 right: `(RGB, Eight)`', C:\Users\cmaza\rust\cvr\src\png.rs:29:5
```

**Comment by fintelia** [comment]
Grepping through the code, the `STRIP_ALPHA` constant is literally never used. I'm really not sure why no error is generated when attempting to use an unsupported transformation but that seems like that should be the first step towards fixing this

**Comment by LeonineKing1199** [comment]
Most definitely.

The good news is, I can technically work around this for the sake of what I'm working on. I'm surprised no one's brought this up before.
