### ISSUE TITLE
Don't verify adler32 checksum by default

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image-png#254]
For lightly compressed images adler32 checksum calculation [accounts for 50% of zlib decompression time](https://github.com/Frommi/miniz_oxide/issues/76), and the efforts to optimize adler32 implementation itself are largely exhausted.

adler32 allows verification of the final uncompressed bitstream; however, the input file integrity is already verified by crc32 in the PNG format. This makes adler32 verification redundant, since the only things it can detect are:

 1. A bug in the zlib decompression implementation
 1. File corruption so subtle that the outer crc32 missed it

Both of these scenarios are so rare that they're not worth the extra runtime overhead in the default configuration.

Disclaimer: my understanding is based on the summary provided [here](https://stackoverflow.com/questions/33914640/adler-32-checksums-in-a-png-file), I'm not an expert on the PNG format.

**Comment by fintelia** [comment]
Even if there _weren't_ an outer checksum, I'd still be quite sympathetic to this idea. File corruption really doesn't seem like much of a concern these days given the reliability guarantees built into lower layers of the stack

**Comment by HeroicKatora** [comment]
I very much like the idea of a builder-style struct for the decoder that would allow configuring these options, and also to turning that validation _off_ by default. At most it should go into some warning output, if the user provides any. 

I also never quite understood what you're supposed to do with a crc failure. Ignore the image? That doesn't seem reasonable, if there's a perfectly fine amount of pixel data. You have a CRC which is supposed to allow you to repair small failures anyways but that's far too expensive on large data blocks—although it would be interesting to offer some optional post processing that at least tries. Is there any of the decoding crates that implements this?

**Comment by Shnatsel** [comment]
PNG was created in the 90s for network use cases specifically. Back then networks were less reliable and could flip bits at random far more frequently than they do now. I assume you're supposed to re-download the image if CRC doesn't match. But that's just my guess.

From what I've seen, image viewers just ignore CRC mismatches.
