### ISSUE TITLE
Publish version including miniz_oxide update

### ISSUE THREAD

**Issue by atouchet** [image-rs/image-png#272]
Currently image has duplicate dependencies of both miniz_oxide 0.3 and 0.4 due to the png and the tiff crates. It appears it was updated in 4424245d09dac4be32e9c19690fcfe3cc1fbdfcc but this isn't included in the latest release. Can a new release be made with this commit?

**Comment by atouchet** [comment]
Hmm, looking at a linked comment it says miniz_oxide 0.4 isn't compatible with Rust 1.3.4. Is that still the case?

**Comment by HeroicKatora** [comment]
I'm not aware of functional changes of `0.4` compared to `0.3`. The main reason for `0.4` in the first place was inclusion into the Rust compiler architecture, and subsequent releases to detect the compiler version to restore compatibility with `1.34.2` again. That being said, it likely does duplicate some amount of code which might cause slight bloat. It's not critical enough to warrant an immediate release but a backport PR would be fine.

**Comment by complexspaces** [comment]
Hi there,

I noticed this issue has been quiet for a bit, but it was mentioned in [this PR](https://github.com/image-rs/image-png/pull/287) as something that was getting closer. Are there any updates here by chance?

**Comment by fintelia** [comment]
I think it is probably time to go ahead and make publish a new release

**Comment by ldm0** [comment]
> I think it is probably time to go ahead and publish a new release

Any update? Thanks.
