### ISSUE TITLE
fuzzit badge not working

### ISSUE THREAD

**Issue by atouchet** [image-rs/image-png#273]
The fuzzit badge in the Readme does not load and when clicked it goes to a login page. Is there an issue with this?

**Comment by SirWindfield** [comment]
Maybe it's related to the fact that fuzzit has been acquired by Gitlab and they shutdown the standalone service.
https://github.com/fuzzitdev/fuzzit
https://about.gitlab.com/blog/2020/10/22/fuzzit-acquisition-journey/

Not sure if this has impact on CI but if so, it might be needed to switch to other similar services or alternatives.
