### ISSUE TITLE
DecodingError - CorruptFlateStream

### ISSUE THREAD

**Issue by ArturKovacs** [image-rs/image-png#294]
The following image causes a `CorruptFlateStream` error when the `read_image` is called on the decoder. Originally posted at: https://github.com/ArturKovacs/emulsion/issues/172

![1443708892 angelfonds_1443660918 crazybear_05ccadee-c566-4e25-9046-f4a437530a2d](https://user-images.githubusercontent.com/291257/105644405-b2edd080-5e95-11eb-8136-2752511ad781.png)

**Comment by fintelia** [comment]
Seems to be fixed
