### ISSUE TITLE
Speed and binary size of this library?

### ISSUE THREAD

**Issue by fzyzcjy** [image-rs/image-png#306]
Hi thanks for this wonderful lib! I wonder (1) how fast is it, and (2) how big is the generated binary executable, compared with traditional `libpng`? Thank you!

**Comment by HeroicKatora** [comment]
Like any rust code that has a few generic structs, and links against `std`, it depends quite a lot on compilation options and the use. If you can avoid too many instantiations then the size is probably ~100 kB extra above the baseline of just linking against `std`? Honestly I can't say that I've evaluate that specifically you'll just need to try. Speed is at least comparable to `libpng`. Issues is also not a Q&A, we have gitter/Elements for this: https://app.element.io/#/room/#image-rs_image:gitter.im

**Comment by fzyzcjy** [comment]
@HeroicKatora Thank you for your reply! 

> If you can avoid too many instantiations then the size is probably ~100 kB extra above the baseline of just linking against std? Honestly I can't say that I've evaluate that specifically you'll just need to try. 

I will try it and thank you.

> Speed is at least comparable to libpng.

Wow that is not slow!
