### ISSUE TITLE
Investigate SIMD support for adler32 in miniz_oxide

### ISSUE THREAD

**Issue by HeroicKatora** [image-rs/image-png#311]
Utilzing the new [simd](https://github.com/Frommi/miniz_oxide/blob/master/miniz_oxide/Cargo.toml#L25) feature in miniz_oxide.

There is some potential pain points:
* Runtime feature detection requires use of `std`, else it is limited to the statically assured cpu features.
* We only have performance gains for `x86`.
* Contains a large amount of `unsafe` code.
* Need to disable some features anyways for `msrv < 1.51`.

**Comment by fintelia** [comment]
Resolved in https://github.com/image-rs/image-png/pull/386
