### ISSUE TITLE
Release 0.17.3?

### ISSUE THREAD

**Issue by repi** [image-rs/image-png#331]
Would it be possible to release a new patch release? 

The latest 0.17.2 published brings in 6 unnecessary `encoding` crates that was fixed back in October last year in  237fe0a9d4f466961ddbf1bf6c5fccb7b2df68b5, but looks like no new release has been made since then.

**Comment by HeroicKatora** [comment]
*Definitely* feel free to file those sooner, if that's a priority for you. From my point of view, PRs since that date were all non-functional in nature so it wasn't a priority. Anyways, release will be come soon due to #330 .

**Comment by repi** [comment]
Thanks!
