### ISSUE TITLE
PNG image is erroneously blank when loaded by `image`

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image-png#346]
This happens in image v0.24.2

## Expected

PNG image loaded and saved right back should have the same content (ignoring color space differences)

## Actual behaviour

The attached image is completely transparent after being loaded and saved by `image`: ![4f14b7aab3a41855378c5517342598b9](https://user-images.githubusercontent.com/291257/177061203-3c6b1002-fb61-4f86-97f6-f0470cb03d84.png)

## Reproduction steps

```rust
use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    use image::io::Reader as ImageReader;
    let input = std::env::args().nth(1).unwrap();
    let output = std::env::args().nth(2).unwrap();
    
    let img = ImageReader::open(input)?.decode()?;
    img.save(output)?;
    Ok(())
}
```

invoked with `image-convert in.png out.png`

**Comment by HeroicKatora** [comment]
>  The tRNS chunk shall not contain more alpha values than there are palette entries, but a tRNS chunk may contain fewer values than there are palette entries. In this case, the alpha value for all remaining palette entries is assumed to be 255.

It seems that color palettes aren't handled properly in `utils::expand_trns_line`.

**Comment by HeroicKatora** [comment]
That actually all seems to be handled as best as possible, as far as I can tell. tRNS consists of 174 nul-bytes.

```
(ChunkType { type: tRNS, critical: false, private: false, reserved: false, safecopy: false }, 174)
```

However, the palette only holds 173 entries! Hence, the detection of an invalid tRNS by pngcheck. Subsequently the whole chunk is most likely ignored by most other decoders.
