### ISSUE TITLE
Failed to load image: Insufficient memory

### ISSUE THREAD

**Issue by micahsnyder** [image-rs/image-png#348]
I found a PNG image that fails to load with `image-png` through `image-rs` with the error message:
`Failed to load image: Insufficient memory`

![170700771-8381ce45-e429-40aa-b183-064b8a944050-insufficient-memory](https://user-images.githubusercontent.com/30635813/178087488-4f055bf8-d5ec-4fd3-bd2d-1d9740f4a5ac.png)

**Comment by HeroicKatora** [comment]
That's a pretty large iTXT chunk of 1314946 bytes in there. The problem: the decoder is allocating a vector with chunk contents and it's not using the limit configured for the pixel matrix, but a separate one
.

**Comment by pm4rcin** [comment]
Here's the same issue with more info https://github.com/image-rs/image/issues/1788

**Comment by JMPJNS** [comment]
its not just text chunks that can be so large. [This image](https://a.storyblok.com/f/192304/3000x3000/cbbdbeb5ce/tech-hero.png) for example has a 2mb caBX (jpeg metadata in a png file) chunk before the image data starts. 
I will try to fix this in a PR but i'm not yet sure how to access the limits in the StreamingDecoder, any helping pointers would be very appreciated.

**Comment by pm4rcin** [comment]
@fintelia all works now https://github.com/danyspin97/wpaperd/issues/21#issuecomment-1994461074. Thanks for fixing!
