### ISSUE TITLE
Bad encoding of image after image::resize

### ISSUE THREAD

**Issue by DLFW** [image-rs/image-png#368]
Hi!
Not sure if I do something stupid or – in case it's a bug – if it's on the  [image](https://github.com/image-rs/image) crate.

However, when I read an image with `image::open`, then resize the image, and then save it with image-png, the resulting file is visually corrupted. When I save it with the `image` crate, it's fine.

## Example

Original:
![test](https://user-images.githubusercontent.com/22507197/208302706-f3c9ccb4-1d7e-4cbb-bcf4-b24c572570fb.png)

Resized and saved with `image-png`:
![test-output-png-encoder](https://user-images.githubusercontent.com/22507197/208302812-5e93aa43-8d12-4f39-8784-74225c995455.png)

Resized and saved with `image::save` is fine:
![test-output-image](https://user-images.githubusercontent.com/22507197/208302733-1f441f1a-f415-4bc5-92d1-b6917802f8ff.png)

## Remarkable

* The problem seems to only occur with 16 bit per color PNG files (at least I could always reproduce it with them and not with 8bpc)
* When I don't scale the image, it works fine
* Intrestingly, when I scale with the [Nearest filter](https://docs.rs/image/0.24.5/image/imageops/enum.FilterType.html), it works. All other filters and the thumbnail operation don't.
* Using image-png 0.17.7

## Minimal example to reproduce

([As project in my GitLab](https://gitlab.com/DLF/rustpngtest/-/tree/example1))

16-bit RGB PNG must exists in `/tmp/test.png`.

```rust
fn main() {
    // Get input with image crate from rgb16 png file
    let in_img = image::open("/tmp/test.png").expect("/tmp/test.png not found");

    assert!(in_img.color() == image::ColorType::Rgb16);

    let out_img = in_img.resize(220, 220, image::imageops::FilterType::Triangle);

    assert!(out_img.color() == image::ColorType::Rgb16);

    // Write it with image - works
    out_img
        .save("/tmp/test-output-image.png")
        .expect("Cannot create output file");

    // Write it with image-png - fails
    let file = std::fs::File::create("/tmp/test-output-png-encoder.png")
        .expect("Cannot create output file");
    let ref mut writer = std::io::BufWriter::new(file);

    let mut encoder = png::Encoder::new(writer, out_img.width(), out_img.height());
    encoder.set_color(png::ColorType::Rgb);
    encoder.set_depth(png::BitDepth::Sixteen);

    let mut writer = encoder.write_header().unwrap();
    writer
        .write_image_data(&out_img.as_bytes().to_vec())
        .unwrap();
}

```

**Comment by fintelia** [comment]
I think there's a pretty good chance that this is related to endian-ness issues. I believe that the PNG crate expects big endian data (since that's what is used in the PNG format) whereas image tries to always use native endian.

**Comment by DLFW** [comment]
That was it!
The thought also popped up for me yesterday afternoon, but I just left it behind because non-scaled images were just fine. My bad. Problem is fixed now. 

@fintelia, the solution you had linked was an excellent guide for me. :+1:  Thank you so much for this very helpful answer!
