### ISSUE TITLE
Large regression in time to complete tests

### ISSUE THREAD

**Issue by okaneco** [image-rs/image-png#385]
It takes ~7-8s on my machine to complete tests with commit b1cceaaf43ff1534c0ba5de1f8f0fc38b8e967b4. This balloons to ~48s in  43646cb995a4a7ace97a8ca96cd0aa7ac75500d3.

`encoder::tests::roundtrip` and `test encoder::tests::roundtrip_stream` take much longer to finish. I can run tests in a different optimization profile to finish faster but posting this issue to see if it's replicable for anyone else.

**Comment by fintelia** [comment]
I also see a regression:
```
7cbf35f  11.4s   (current main)
43646cb  11.4s
b1cceaa  4.0s
```

**Comment by fintelia** [comment]
#384 upgrades fdeflate and should fix this
