### ISSUE TITLE
afl binary cannot be built

### ISSUE THREAD

**Issue by yongmandooo** [image-rs/image-png#406]
after "cargo afl build", there is an error.

`   Compiling png-afl v0.2.0 (/home/kym000131/fuzzing_set/Rust/image-png/png-afl)
error: declaration of a `no_mangle` function
  --> src/main.rs:11:1
   |
11 | #[no_mangle]
   | ^^^^^^^^^^^^
   |
   = note: the linker's behavior with multiple libraries exporting duplicate symbol names is undefined and Rust cannot provide guarantees when you manually override them
note: the lint level is defined here
  --> src/main.rs:2:11
   |
2  | #![forbid(unsafe_code)]
   |           ^^^^^^^^^^^

error[E0308]: mismatched types
  --> src/main.rs:19:9
   |
19 |     let (info, mut reader) = decoder.read_info().map_err(|_| ())?;
   |         ^^^^^^^^^^^^^^^^^^   ------------------------------------ this expression has type `Reader<&[u8]>`
   |         |
   |         expected `Reader<&[u8]>`, found `(_, _)`
   |
   = note: expected struct `Reader<&[u8]>`
               found tuple `(_, _)``
              
I think there is a problem in png-afl/src/main.rs

**Comment by whtsht** [comment]
Since [detect_odr_violations=0 is now set by default](https://github.com/rust-fuzz/cargo-fuzz/pull/32), you can delete the code that causes the first error.

The second mismatched types error easy to fix.
