### ISSUE TITLE
Panic on decoding a crafted image: `chunk size must be non-zero`

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image-png#444]
The following file found by the in-tree fuzzer results in a panic when decoded:

```
thread '<unnamed>' panicked at image-png/src/decoder/mod.rs:534:18:
chunk size must be non-zero
```

[crash-127a81c8af6d6817feb3c560e0d45c80047ac6d5.png.gz](https://github.com/image-rs/image-png/files/13799528/crash-127a81c8af6d6817feb3c560e0d45c80047ac6d5.png.gz)

(gzipped so that github would accept the upload)

**Comment by fintelia** [comment]
The crash is on this line:
https://github.com/image-rs/image-png/blob/d761f1614aef9a119e74cb2808c7af43a422c4c1/src/decoder/mod.rs#L534

**Comment by Shnatsel** [comment]
Likely a duplicate of #438
