### ISSUE TITLE
Infinite loop on decoding a crafted image

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image-png#446]
The following image causes an infinite loop when decoded: [timeout-3d68b7a54d90b24caaf5136dce8e35f7417b43d7](https://github.com/image-rs/image-png/assets/291257/9934015e-0267-468d-9f69-20b5324b0a1d)

Found by the cargo-fuzz `decode` harness. Tested on commit d761f1614aef9a119e74cb2808c7af43a422c4c1

**Comment by Shnatsel** [comment]
Might be a duplicate of #217

**Comment by fintelia** [comment]
Seems it was fixed by #447
