### ISSUE TITLE
Crash in `parse_ztxt`

### ISSUE THREAD

**Issue by micahsnyder** [image-rs/image-png#476]
A team using the png crate through libclamav encountered an image that triggers a crash. They shared this stack trace with me.  
![image](https://github.com/image-rs/image-png/assets/30635813/96ac3d3e-f29e-4457-9d75-efd2333f74c2)

Their application was scanning network traffic and unfortunately they seem unable to provide the specific file which causes the crash. 
 
This was with png crate v0.17.10. So the line in question I guess is https://github.com/image-rs/image-png/blob/v0.17.10/src/decoder/stream.rs#L1253

I don't know what to make of it. Do you see anything here which may crash?

**Comment by fintelia** [comment]
I wonder if this is related to https://github.com/image-rs/image-png/pull/456.

**Comment by micahsnyder** [comment]
That seems plausible. I'll see if I can get the other team to upgrade to 0.17.13 to see if the crash goes away.  When they first came to me you were on 0.17.11, ha! I didn't even see this change or the 2 subsequent releases. 🙇  I'll get back to you.
