### ISSUE TITLE
APNG decoder doesn't seem to handle `BlendOp::Over`

### ISSUE THREAD

**Issue by thomcc** [image-rs/image-png#491]
Hi, sorry in advance if I'm missing something (possible, but I don't think so or I wouldn't be filing an issue).

It doesn't appear that this crate correctly decodes APNG files that use `BlendOp::Over`. I think the issue is around https://github.com/image-rs/image-png/blob/2cfde02d3a50c531e3160023d1e4b0ae92869f4a/src/decoder/mod.rs#L540-L561, which seems to (if I'm reading correctly) unconditionally overwrite the subframe with the new (sub)frame data, which is only correct if the blend op in the relevant frame control chunk was BlendOp::Source. If the op was `BlendOp::Over`, then the new subframe data needs to be composited on top of the old frame, which doesn't seem to happen.

Sorry again if I'm missing something. I did a search to see if this happens elsewhere, and the blend op doesn't appear to get used at all, which is pretty suspicious even if my analysis above is incorrect in some way.

Admittedly, `BlendOp::Over` is probably fairly rare.

**Comment by fintelia** [comment]
This crate doesn't do any compositing of frames. For better or worse, [that is implemented in the image crate](https://github.com/image-rs/image/blob/e176cd414ac6cc73909ff162e5d0b677f9d4fb08/src/codecs/png.rs#L262) instead.

**Comment by thomcc** [comment]
Fair enough!

**Comment by anforowicz** [comment]
FWIW when working on `skia/experimental/rust_png` I am implementing blending outside of the `png` crate: http://review.skia.org/911037.  And I think this is not entirely unexpected - for example `SkWebpCodec` also [implements blending](https://source.chromium.org/chromium/chromium/src/+/main:third_party/skia/src/codec/SkWebpCodec.cpp;l=337-366;drc=c9943f14039faa721b02c64b5fad42dfb87af013) outside of `libwebp`.
