### ISSUE TITLE
Feature Request: bKGD info

### ISSUE THREAD

**Issue by ocpkn** [image-rs/image-png#536]
Currently, there is no straightforward way to access an image's background color from the `bKGD` chunk.

`png::stream::StreamingDecoder` lacks a method to parse these chunks and `png::common::Info` lacks a field for this data. This chunk type is in common use and it should be accessible to the client.

The benefits of this would include displaying images with the intended background color as well as combining an image's alpha channel with the background color to produce an opaque image.

**Comment by kornelski** [comment]
Is kBGD actually implemented by anyone? I think IE6 was the last application that couldn't handle alpha and had a reason to use it. I haven't seen any other application that used it.

**Comment by ocpkn** [comment]
Some programs will erase color data from transparent pixels when exporting an image to PNG and/or save the background color in a bKGD chunk. The current version of GIMP does both by default.

**Comment by fintelia** [comment]
Seems reasonable to add bKGD support. Feel free to make a PR if you'd like, there's been a few recent PRs adding other chunks that you can use for reference
