### ISSUE TITLE
Performance issues?

### ISSUE THREAD

**Issue by hasufell** [image-rs/image-png#59]
This is not a definite statement, but when I compare using [gdk_pixbuf_new_from_file](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-File-Loading.html#gdk-pixbuf-new-from-file) directly, which loads in e.g. png images... but Instead I do `!include_bytes(image)`, then decode with this png crate and feed it to [gdk_pixbuf_new_from_data](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-Image-Data-in-Memory.html#gdk-pixbuf-new-from-data), then I see quite a performance difference. Those things should almost roughly do the same, no?

**Comment by LaylConway** [comment]
`include_bytes!()` loads in the file at compile-time while `gdk_pixbuf_new_from_file` loads in the file at runtime. In both cases of course you're reading data off the disk, but `include_bytes!()` embeds the data in the executable, most likely causing it to be loaded before the performance counter you're using.

**Comment by hasufell** [comment]
I mean that `gdk_pixbuf_new_from_file` is faster, which does its own decoding.

**Comment by LaylConway** [comment]
Are you running in debug or release? What are the precise load times you're getting?

**Comment by oyvindln** [comment]
Is it a massive performance difference? This crate isn't quite as fast as libpng yet.

**Comment by martinlindhe** [comment]
This issue has not seen updates in a long while, so closing it.

If there is specific issues or suggestions around performance, please open a new issue.
