### ISSUE TITLE
Add maintainers to that crate

### ISSUE THREAD

**Issue by nox** [image-rs/image-png#95]
@bvssvni Would you mind adding maintainers to that crate? https://github.com/PistonDevelopers/image-png/pull/94 needs to be merged.

**Comment by nox** [comment]
Cc @nwin

**Comment by bvssvni** [comment]
@nox You can self merge when you know what you are doing and don't want to wait for a review: https://github.com/PistonDevelopers/piston/issues/674

**Comment by HeroicKatora** [comment]
Closing this, the PR was merged and a bit outdated with organization change as well.
